### ISSUE TITLE
[Suggestion] New paper

### ISSUE THREAD

**Issue by macio232** [simulation-based-inference/simulation-based-inference.github.io#113]
Title: Calibrating Neural Simulation-Based Inference with Differentiable Coverage Probability

Short description: A regularizer for NRE and NPE aimed at reducing the overconfidence of approximate posterior

Link to paper: https://arxiv.org/abs/2310.13402 (Neurips 23 poster)

**Comment by macio232** [comment]
Why did it go to "Uncategorized" and not "Statistics"?

**Comment by JasonLo** [comment]
fixed
