### ISSUE TITLE
Add a button to create an issue to remove spurious / irrelevant papers

### ISSUE THREAD

**Issue by cranmer** [simulation-based-inference/simulation-based-inference.github.io#23]
We might have papers that are irrelevant that are added from the search. 
Maybe we can add a button on a page that would create an issue (or maybe even a PR) to remove a paper.

This might require extending the database so that the paper is an entry, but considered irrelevant.

**Comment by JasonLo** [comment]
Same as #24, I had added a remove paper link in [papers section](http://simulation-based-inference.org/papers/).

For now, I will just manually remove it after receiving a request, if there are many remove demand, we can consider using a web form along with an approval mechanism. Marking this issue as wontfix for now.
