### ISSUE TITLE
Create mechanism to add papers manually

### ISSUE THREAD

**Issue by cranmer** [simulation-based-inference/simulation-based-inference.github.io#24]
It would be nice to create mechanism to add papers manually. This would need to update the db as well as add the .md file.

**Comment by JasonLo** [comment]
I had added a submit new paper link in [papers section](http://simulation-based-inference.org/papers/). 

For now, I will just manually after receiving a request, if there are many new paper submission demand, we can consider using a web form along with an approval mechanism. Marking this issue as wontfix for now
