### ISSUE TITLE
[Feature]: add social media card

### ISSUE THREAD

**Issue by cranmer** [simulation-based-inference/simulation-based-inference.github.io#51]
This is what it looks like. Need to think about what image to show 

![E47FD7A0-0349-419A-8006-CF9C9FAF43FC](https://github.com/simulation-based-inference/simulation-based-inference.github.io/assets/4458890/d4622f26-5aa0-4241-a414-bbba412c0600)

**Comment by JasonLo** [comment]
How about journal / source icon? For example:

arXiv:
![image](https://github.com/simulation-based-inference/simulation-based-inference.github.io/assets/1927986/f557a81e-607f-4206-8a7f-79698a20c9e4)

bioraxiv:
![image](https://github.com/simulation-based-inference/simulation-based-inference.github.io/assets/1927986/7fa8b7e2-39e9-43a3-9249-ad31a7eaaedf)

**Comment by cranmer** [comment]
That could work. I was thinking more along the lies of the SBI site itself though. Maybe just a simple image with SBI in it for now?

**Comment by JasonLo** [comment]
Addressed in #58

Now the social sharing looks like this on twitter:
![image](https://github.com/simulation-based-inference/simulation-based-inference.github.io/assets/1927986/a1282422-dd86-4e45-b599-1c26ea5f15a0)
