### ISSUE TITLE
[Concern]: Talks not papers

### ISSUE THREAD

**Issue by cranmer** [simulation-based-inference/simulation-based-inference.github.io#54]
I noticed the scraping is picking up lots of talks.

Some come from 
meetingorganizer.copernicus.org

another
http://simulation-based-inference.org/uncategorized/2022/12/31/milky-way-structure-revealed-by-galactic-hii-regions/

These are interesting, but maybe we should try to classify them differently.  Potentially papers, software, talks. That may be difficult to identify though. One would be to restrict to arXiv, bioRxiv, etc. But there are fully published papers as well that don't have obvious entry in arXiv. Hmm.

**Comment by JasonLo** [comment]
We have a `journal` field in the back-end database. The current set of `journal` includes:

{'APS', 'Elsevier', 'Taylor & Francis', 'aanda.org', 'academic.oup.com', 'ai.ku.dk', 'arxiv.org', 'biorxiv.org', 'cell.com',
 'coschroeder.github.io', 'dial.uclouvain.be', 'drops.dagstuhl.de', 'ethos.bl.uk', 'hal.science', 'hess.copernicus.org',
 'iase-web.org','ideas.repec.org', 'ieeexplore.ieee.org', 'iopscience.iop.org', 'joss.theoj.org',  'journals.lww.com',
 'journals.plos.org', 'kent.ac.uk', 'mdpi.com', 'meetingorganizer.copernicus.org', 'openreview.net', 'orbi.uliege.be',
 'peerj.com', 'proceedings.mlr.press', 'proceedings.neurips.cc', 'repository.lib.ncsu.edu', 'riull.ull.es', 'search.proquest.com',
 'tobias-lib.ub.uni-tuebingen.de', 'ui.adsabs.harvard.edu', 'wp.lancs.ac.uk'}

Certain entries are clearly not journals, for which we can manually curate a whitelist and conceal the remaining items from the user interface.

**Comment by JasonLo** [comment]
Incorporated a basic white list system in #66.

The remaining items classified as "miscellaneous" need to be sorted into a separate section.
