### ISSUE TITLE
[Feature]: Use YAML to replace SQlite

### ISSUE THREAD

**Issue by JasonLo** [simulation-based-inference/simulation-based-inference.github.io#62]
**Is your feature request related to a problem? Please describe.**
SQLite is kind of difficult to edit directly

**Describe the solution you'd like**
Use a giant YAML file to store the data.

**Comment by JasonLo** [comment]
Upon reconsideration, perhaps a .csv file would be adequate, and it can be conveniently handled using pandas.

**Comment by cranmer** [comment]
I prefer yaml to be honest.

**Comment by JasonLo** [comment]
Addressed in #72
